"""init

Revision ID: 029e1cd8d45d
Revises: 463910b431c1
Create Date: 2023-09-26 23:49:40.040902

"""

# revision identifiers, used by Alembic.
revision = '029e1cd8d45d'
down_revision = '463910b431c1'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
