"""init

Revision ID: 02fad0564e2c
Revises: f04e886363e9
Create Date: 2023-09-27 11:43:55.795515

"""

# revision identifiers, used by Alembic.
revision = '02fad0564e2c'
down_revision = 'f04e886363e9'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
