"""init

Revision ID: 032c8bc4e1fb
Revises: 5da66a206286
Create Date: 2023-09-28 00:12:48.255802

"""

# revision identifiers, used by Alembic.
revision = '032c8bc4e1fb'
down_revision = '5da66a206286'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
