"""init

Revision ID: 0763aa9c6555
Revises: a0a6a7b7a2d2
Create Date: 2023-09-27 23:48:43.400791

"""

# revision identifiers, used by Alembic.
revision = '0763aa9c6555'
down_revision = 'a0a6a7b7a2d2'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
