"""init

Revision ID: 09e7486fb4e8
Revises: c8d176c5c4ca
Create Date: 2023-09-26 23:07:58.570571

"""

# revision identifiers, used by Alembic.
revision = '09e7486fb4e8'
down_revision = 'c8d176c5c4ca'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
