"""init

Revision ID: 0be3a1f87c20
Revises: f7b0a1eaa12c
Create Date: 2023-09-26 23:14:22.905374

"""

# revision identifiers, used by Alembic.
revision = '0be3a1f87c20'
down_revision = 'f7b0a1eaa12c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
