"""init

Revision ID: 12aa39ebda5e
Revises: 1c8ad7c9dc4b
Create Date: 2023-09-27 00:56:01.061740

"""

# revision identifiers, used by Alembic.
revision = '12aa39ebda5e'
down_revision = '1c8ad7c9dc4b'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
