"""init

Revision ID: 1387dc3c0007
Revises: 51eae0eb833b
Create Date: 2023-09-27 22:20:25.303853

"""

# revision identifiers, used by Alembic.
revision = '1387dc3c0007'
down_revision = '51eae0eb833b'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
