"""init

Revision ID: 13ab059719ba
Revises: 552de41f4d92
Create Date: 2023-09-27 01:49:08.864526

"""

# revision identifiers, used by Alembic.
revision = '13ab059719ba'
down_revision = '552de41f4d92'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
