"""init

Revision ID: 1afe5ab43ca5
Revises: dd33cb03d01f
Create Date: 2023-09-26 21:41:46.895728

"""

# revision identifiers, used by Alembic.
revision = '1afe5ab43ca5'
down_revision = 'dd33cb03d01f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
