"""init

Revision ID: 1c8ad7c9dc4b
Revises: 97dc8af6b0fc
Create Date: 2023-09-27 00:55:42.378699

"""

# revision identifiers, used by Alembic.
revision = '1c8ad7c9dc4b'
down_revision = '97dc8af6b0fc'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
