"""init

Revision ID: 20a6be05a867
Revises: b3a2b059b847
Create Date: 2023-09-27 00:31:59.209428

"""

# revision identifiers, used by Alembic.
revision = '20a6be05a867'
down_revision = 'b3a2b059b847'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
