"""init

Revision ID: 2887a3fa0cee
Revises: 414302ee45fc
Create Date: 2023-09-26 23:55:49.023023

"""

# revision identifiers, used by Alembic.
revision = '2887a3fa0cee'
down_revision = '414302ee45fc'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
