"""init

Revision ID: 28a84394e3d7
Revises: d9818eb37d56
Create Date: 2023-09-27 23:06:58.099417

"""

# revision identifiers, used by Alembic.
revision = '28a84394e3d7'
down_revision = 'd9818eb37d56'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
