"""init

Revision ID: 2af54bb63ba8
Revises: 59242257e6f7
Create Date: 2023-09-27 01:09:46.190192

"""

# revision identifiers, used by Alembic.
revision = '2af54bb63ba8'
down_revision = '59242257e6f7'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
