"""init

Revision ID: 2b670953e5d8
Revises: cf2fbf4019a0
Create Date: 2023-09-27 02:00:49.761545

"""

# revision identifiers, used by Alembic.
revision = '2b670953e5d8'
down_revision = 'cf2fbf4019a0'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
