"""init

Revision ID: 2b6e59e880e5
Revises: 5d2716205033
Create Date: 2023-09-27 23:23:11.970810

"""

# revision identifiers, used by Alembic.
revision = '2b6e59e880e5'
down_revision = '5d2716205033'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
