"""init

Revision ID: 2e91bb8e9bd6
Revises: 0763aa9c6555
Create Date: 2023-09-27 23:50:25.846188

"""

# revision identifiers, used by Alembic.
revision = '2e91bb8e9bd6'
down_revision = '0763aa9c6555'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
