"""init

Revision ID: 307b77a303d4
Revises: c1fa81c8bfb4
Create Date: 2023-09-28 00:03:39.101799

"""

# revision identifiers, used by Alembic.
revision = '307b77a303d4'
down_revision = 'c1fa81c8bfb4'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
