"""init

Revision ID: 30e6c633bf0c
Revises: 3dff1332cb4c
Create Date: 2023-09-27 21:44:18.543324

"""

# revision identifiers, used by Alembic.
revision = '30e6c633bf0c'
down_revision = '3dff1332cb4c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
