"""init

Revision ID: 3547b0de20af
Revises: 77c4a4817658
Create Date: 2023-09-26 23:16:51.969222

"""

# revision identifiers, used by Alembic.
revision = '3547b0de20af'
down_revision = '77c4a4817658'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
