"""init

Revision ID: 38635fc99df3
Revises: a721526359ce
Create Date: 2023-09-27 21:38:55.947568

"""

# revision identifiers, used by Alembic.
revision = '38635fc99df3'
down_revision = 'a721526359ce'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
