"""init

Revision ID: 38ea7f697093
Revises: c17ca45e704a
Create Date: 2023-09-26 23:11:45.671351

"""

# revision identifiers, used by Alembic.
revision = '38ea7f697093'
down_revision = 'c17ca45e704a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
