"""init

Revision ID: 3b4e9e65845c
Revises: db4ec04e572e
Create Date: 2023-09-27 21:26:38.223095

"""

# revision identifiers, used by Alembic.
revision = '3b4e9e65845c'
down_revision = 'db4ec04e572e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
