"""init

Revision ID: 3b69730873e8
Revises: 83cedf2772a6
Create Date: 2023-09-27 01:14:15.032949

"""

# revision identifiers, used by Alembic.
revision = '3b69730873e8'
down_revision = '83cedf2772a6'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
