"""init

Revision ID: 3dff1332cb4c
Revises: 4093dfaea68b
Create Date: 2023-09-27 21:42:59.810479

"""

# revision identifiers, used by Alembic.
revision = '3dff1332cb4c'
down_revision = '4093dfaea68b'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
