"""init

Revision ID: 3e78adcbfb5e
Revises: 2887a3fa0cee
Create Date: 2023-09-27 00:14:43.905588

"""

# revision identifiers, used by Alembic.
revision = '3e78adcbfb5e'
down_revision = '2887a3fa0cee'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
