"""init

Revision ID: 4093dfaea68b
Revises: d364fbab4f04
Create Date: 2023-09-27 21:42:33.605998

"""

# revision identifiers, used by Alembic.
revision = '4093dfaea68b'
down_revision = 'd364fbab4f04'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
