"""init

Revision ID: 414302ee45fc
Revises: ef674a0c3579
Create Date: 2023-09-26 23:55:40.716735

"""

# revision identifiers, used by Alembic.
revision = '414302ee45fc'
down_revision = 'ef674a0c3579'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
