"""init

Revision ID: 41783a491731
Revises: 13ab059719ba
Create Date: 2023-09-27 01:51:42.225707

"""

# revision identifiers, used by Alembic.
revision = '41783a491731'
down_revision = '13ab059719ba'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
