"""init

Revision ID: 43d689823193
Revises: 91e719d410d2
Create Date: 2023-09-27 01:30:46.174542

"""

# revision identifiers, used by Alembic.
revision = '43d689823193'
down_revision = '91e719d410d2'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
