"""init

Revision ID: 44f14d1f2e25
Revises: d2c21515a35e
Create Date: 2023-09-27 01:32:06.908102

"""

# revision identifiers, used by Alembic.
revision = '44f14d1f2e25'
down_revision = 'd2c21515a35e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
