"""init

Revision ID: 45a8f9324678
Revises: 85d1af679180
Create Date: 2023-09-27 22:53:34.721250

"""

# revision identifiers, used by Alembic.
revision = '45a8f9324678'
down_revision = '85d1af679180'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
