"""init

Revision ID: 463910b431c1
Revises: d30911eb15a9
Create Date: 2023-09-26 23:34:07.753172

"""

# revision identifiers, used by Alembic.
revision = '463910b431c1'
down_revision = 'd30911eb15a9'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
