"""init

Revision ID: 49977b4690fa
Revises: 2e91bb8e9bd6
Create Date: 2023-09-27 23:54:59.216492

"""

# revision identifiers, used by Alembic.
revision = '49977b4690fa'
down_revision = '2e91bb8e9bd6'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
