"""init

Revision ID: 4d0d21b5c100
Revises: d2af980ee4e7
Create Date: 2023-09-26 23:09:46.386285

"""

# revision identifiers, used by Alembic.
revision = '4d0d21b5c100'
down_revision = 'd2af980ee4e7'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
