"""init

Revision ID: 4d1a3530679d
Revises: 3547b0de20af
Create Date: 2023-09-26 23:17:26.652422

"""

# revision identifiers, used by Alembic.
revision = '4d1a3530679d'
down_revision = '3547b0de20af'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
