"""init

Revision ID: 505765dcc1e2
Revises: 7d54255bb8b5
Create Date: 2023-09-26 22:48:07.493844

"""

# revision identifiers, used by Alembic.
revision = '505765dcc1e2'
down_revision = '7d54255bb8b5'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
