"""init

Revision ID: 51eae0eb833b
Revises: 98f11f17a861
Create Date: 2023-09-27 22:18:32.285891

"""

# revision identifiers, used by Alembic.
revision = '51eae0eb833b'
down_revision = '98f11f17a861'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
