"""init

Revision ID: 552de41f4d92
Revises: 79328c6804f3
Create Date: 2023-09-27 01:43:24.451898

"""

# revision identifiers, used by Alembic.
revision = '552de41f4d92'
down_revision = '79328c6804f3'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
