"""init

Revision ID: 59242257e6f7
Revises: eeab15bb5dcc
Create Date: 2023-09-27 01:09:09.822470

"""

# revision identifiers, used by Alembic.
revision = '59242257e6f7'
down_revision = 'eeab15bb5dcc'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
