"""init

Revision ID: 5d2716205033
Revises: f582cc414e33
Create Date: 2023-09-27 23:22:49.629405

"""

# revision identifiers, used by Alembic.
revision = '5d2716205033'
down_revision = 'f582cc414e33'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
