"""init

Revision ID: 5da66a206286
Revises: 91251fc9baac
Create Date: 2023-09-28 00:11:10.766462

"""

# revision identifiers, used by Alembic.
revision = '5da66a206286'
down_revision = '91251fc9baac'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
