"""init

Revision ID: 61383f95ba09
Revises: bdaf0a4c5546
Create Date: 2023-09-27 23:08:24.705909

"""

# revision identifiers, used by Alembic.
revision = '61383f95ba09'
down_revision = 'bdaf0a4c5546'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
