"""init

Revision ID: 63840f6964e9
Revises: b6b5ef968c3e
Create Date: 2023-09-26 23:15:56.459322

"""

# revision identifiers, used by Alembic.
revision = '63840f6964e9'
down_revision = 'b6b5ef968c3e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
