"""init

Revision ID: 64c2c2760f55
Revises: d8cf074c2218
Create Date: 2023-09-27 01:24:46.421885

"""

# revision identifiers, used by Alembic.
revision = '64c2c2760f55'
down_revision = 'd8cf074c2218'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
