"""init

Revision ID: 68e6cff61e79
Revises: 90d8b9425be1
Create Date: 2023-09-27 23:34:46.764387

"""

# revision identifiers, used by Alembic.
revision = '68e6cff61e79'
down_revision = '90d8b9425be1'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
