"""init

Revision ID: 6a9aac0661ec
Revises: 2b670953e5d8
Create Date: 2023-09-27 02:05:46.412534

"""

# revision identifiers, used by Alembic.
revision = '6a9aac0661ec'
down_revision = '2b670953e5d8'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
