"""init

Revision ID: 6dae11b3113f
Revises: 02fad0564e2c
Create Date: 2023-09-27 11:55:47.169777

"""

# revision identifiers, used by Alembic.
revision = '6dae11b3113f'
down_revision = '02fad0564e2c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
