"""init

Revision ID: 6f560f4753f2
Revises: 703f8785bb2f
Create Date: 2023-09-27 00:54:42.942630

"""

# revision identifiers, used by Alembic.
revision = '6f560f4753f2'
down_revision = '703f8785bb2f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
