"""init

Revision ID: 703f8785bb2f
Revises: 20a6be05a867
Create Date: 2023-09-27 00:53:59.090100

"""

# revision identifiers, used by Alembic.
revision = '703f8785bb2f'
down_revision = '20a6be05a867'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
