"""init

Revision ID: 751825c1342c
Revises: 1afe5ab43ca5
Create Date: 2023-09-26 21:59:21.046151

"""

# revision identifiers, used by Alembic.
revision = '751825c1342c'
down_revision = '1afe5ab43ca5'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
