"""init

Revision ID: 77c4a4817658
Revises: 63840f6964e9
Create Date: 2023-09-26 23:16:21.963288

"""

# revision identifiers, used by Alembic.
revision = '77c4a4817658'
down_revision = '63840f6964e9'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
