"""init

Revision ID: 79328c6804f3
Revises: 44f14d1f2e25
Create Date: 2023-09-27 01:37:04.708911

"""

# revision identifiers, used by Alembic.
revision = '79328c6804f3'
down_revision = '44f14d1f2e25'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
