"""init

Revision ID: 7a0e4c386d59
Revises: bb61508346a0
Create Date: 2023-09-27 22:01:36.254316

"""

# revision identifiers, used by Alembic.
revision = '7a0e4c386d59'
down_revision = 'bb61508346a0'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
