"""init

Revision ID: 7d54255bb8b5
Revises: fcf494ff0cc2
Create Date: 2023-09-26 22:48:01.782375

"""

# revision identifiers, used by Alembic.
revision = '7d54255bb8b5'
down_revision = 'fcf494ff0cc2'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
