"""init

Revision ID: 83cedf2772a6
Revises: 2af54bb63ba8
Create Date: 2023-09-27 01:13:25.386884

"""

# revision identifiers, used by Alembic.
revision = '83cedf2772a6'
down_revision = '2af54bb63ba8'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
