"""init

Revision ID: 85d1af679180
Revises: 951e939ffe8d
Create Date: 2023-09-27 22:52:43.558216

"""

# revision identifiers, used by Alembic.
revision = '85d1af679180'
down_revision = '951e939ffe8d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
