"""init

Revision ID: 8c27923613f0
Revises: b331c06d1dde
Create Date: 2023-09-26 22:13:18.801940

"""

# revision identifiers, used by Alembic.
revision = '8c27923613f0'
down_revision = 'b331c06d1dde'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
