"""init

Revision ID: 8c5913ad475c
Revises: 30e6c633bf0c
Create Date: 2023-09-27 21:58:24.942119

"""

# revision identifiers, used by Alembic.
revision = '8c5913ad475c'
down_revision = '30e6c633bf0c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
