"""init

Revision ID: 90d8b9425be1
Revises: ed7b6cdb3a7d
Create Date: 2023-09-27 23:34:29.408155

"""

# revision identifiers, used by Alembic.
revision = '90d8b9425be1'
down_revision = 'ed7b6cdb3a7d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
