"""init

Revision ID: 91251fc9baac
Revises: 307b77a303d4
Create Date: 2023-09-28 00:04:44.547825

"""

# revision identifiers, used by Alembic.
revision = '91251fc9baac'
down_revision = '307b77a303d4'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
