"""init

Revision ID: 9251cccdc35d
Revises: 8c27923613f0
Create Date: 2023-09-26 22:19:52.927922

"""

# revision identifiers, used by Alembic.
revision = '9251cccdc35d'
down_revision = '8c27923613f0'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
