"""init

Revision ID: 951e939ffe8d
Revises: d10cc1f95bd5
Create Date: 2023-09-27 22:45:04.312814

"""

# revision identifiers, used by Alembic.
revision = '951e939ffe8d'
down_revision = 'd10cc1f95bd5'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
