"""init

Revision ID: 97dc8af6b0fc
Revises: 6f560f4753f2
Create Date: 2023-09-27 00:55:24.859445

"""

# revision identifiers, used by Alembic.
revision = '97dc8af6b0fc'
down_revision = '6f560f4753f2'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
