"""init

Revision ID: 98f11f17a861
Revises: e27403559068
Create Date: 2023-09-27 22:03:14.758586

"""

# revision identifiers, used by Alembic.
revision = '98f11f17a861'
down_revision = 'e27403559068'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
