"""init

Revision ID: a721526359ce
Revises: 3b4e9e65845c
Create Date: 2023-09-27 21:32:19.964378

"""

# revision identifiers, used by Alembic.
revision = 'a721526359ce'
down_revision = '3b4e9e65845c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
