"""init

Revision ID: ab916f28ad47
Revises: 61383f95ba09
Create Date: 2023-09-27 23:10:21.910016

"""

# revision identifiers, used by Alembic.
revision = 'ab916f28ad47'
down_revision = '61383f95ba09'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
