"""init

Revision ID: ab9c789aaa56
Revises: ab916f28ad47
Create Date: 2023-09-27 23:12:04.690045

"""

# revision identifiers, used by Alembic.
revision = 'ab9c789aaa56'
down_revision = 'ab916f28ad47'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
