"""init

Revision ID: b331c06d1dde
Revises: e622e2d3a32b
Create Date: 2023-09-26 22:05:23.933142

"""

# revision identifiers, used by Alembic.
revision = 'b331c06d1dde'
down_revision = 'e622e2d3a32b'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
