"""init

Revision ID: b3a2b059b847
Revises: 3e78adcbfb5e
Create Date: 2023-09-27 00:31:28.219513

"""

# revision identifiers, used by Alembic.
revision = 'b3a2b059b847'
down_revision = '3e78adcbfb5e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
