"""init

Revision ID: b6b5ef968c3e
Revises: 0be3a1f87c20
Create Date: 2023-09-26 23:15:29.217841

"""

# revision identifiers, used by Alembic.
revision = 'b6b5ef968c3e'
down_revision = '0be3a1f87c20'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
