"""init

Revision ID: bb61508346a0
Revises: 8c5913ad475c
Create Date: 2023-09-27 22:00:06.188763

"""

# revision identifiers, used by Alembic.
revision = 'bb61508346a0'
down_revision = '8c5913ad475c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
