"""init

Revision ID: bdaf0a4c5546
Revises: 28a84394e3d7
Create Date: 2023-09-27 23:07:43.948734

"""

# revision identifiers, used by Alembic.
revision = 'bdaf0a4c5546'
down_revision = '28a84394e3d7'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
