"""init

Revision ID: c17ca45e704a
Revises: 4d0d21b5c100
Create Date: 2023-09-26 23:10:58.513987

"""

# revision identifiers, used by Alembic.
revision = 'c17ca45e704a'
down_revision = '4d0d21b5c100'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
