"""init

Revision ID: c1fa81c8bfb4
Revises: 49977b4690fa
Create Date: 2023-09-27 23:57:34.805791

"""

# revision identifiers, used by Alembic.
revision = 'c1fa81c8bfb4'
down_revision = '49977b4690fa'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
