"""init

Revision ID: c8d176c5c4ca
Revises: 505765dcc1e2
Create Date: 2023-09-26 22:57:25.118427

"""

# revision identifiers, used by Alembic.
revision = 'c8d176c5c4ca'
down_revision = '505765dcc1e2'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
