"""init

Revision ID: cf2fbf4019a0
Revises: 41783a491731
Create Date: 2023-09-27 01:56:35.752330

"""

# revision identifiers, used by Alembic.
revision = 'cf2fbf4019a0'
down_revision = '41783a491731'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
