"""init

Revision ID: d10cc1f95bd5
Revises: 1387dc3c0007
Create Date: 2023-09-27 22:20:52.942401

"""

# revision identifiers, used by Alembic.
revision = 'd10cc1f95bd5'
down_revision = '1387dc3c0007'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
