"""init

Revision ID: d2c21515a35e
Revises: 43d689823193
Create Date: 2023-09-27 01:31:01.612524

"""

# revision identifiers, used by Alembic.
revision = 'd2c21515a35e'
down_revision = '43d689823193'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
