"""init

Revision ID: d30911eb15a9
Revises: 4d1a3530679d
Create Date: 2023-09-26 23:22:32.092765

"""

# revision identifiers, used by Alembic.
revision = 'd30911eb15a9'
down_revision = '4d1a3530679d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
