"""init

Revision ID: d364fbab4f04
Revises: 38635fc99df3
Create Date: 2023-09-27 21:41:27.038905

"""

# revision identifiers, used by Alembic.
revision = 'd364fbab4f04'
down_revision = '38635fc99df3'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
