"""init

Revision ID: d8cf074c2218
Revises: 3b69730873e8
Create Date: 2023-09-27 01:21:07.213645

"""

# revision identifiers, used by Alembic.
revision = 'd8cf074c2218'
down_revision = '3b69730873e8'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
