"""init

Revision ID: d9818eb37d56
Revises: e32b6263da04
Create Date: 2023-09-27 23:06:27.103254

"""

# revision identifiers, used by Alembic.
revision = 'd9818eb37d56'
down_revision = 'e32b6263da04'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
