"""init

Revision ID: db4ec04e572e
Revises: 6dae11b3113f
Create Date: 2023-09-27 11:58:02.641407

"""

# revision identifiers, used by Alembic.
revision = 'db4ec04e572e'
down_revision = '6dae11b3113f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
