"""init

Revision ID: dcb90affd769
Revises: 751825c1342c
Create Date: 2023-09-26 22:04:47.797665

"""

# revision identifiers, used by Alembic.
revision = 'dcb90affd769'
down_revision = '751825c1342c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
