"""init

Revision ID: e27403559068
Revises: 7a0e4c386d59
Create Date: 2023-09-27 22:03:05.787687

"""

# revision identifiers, used by Alembic.
revision = 'e27403559068'
down_revision = '7a0e4c386d59'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
