"""init

Revision ID: e32b6263da04
Revises: 45a8f9324678
Create Date: 2023-09-27 22:54:19.912867

"""

# revision identifiers, used by Alembic.
revision = 'e32b6263da04'
down_revision = '45a8f9324678'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
