"""init

Revision ID: e622e2d3a32b
Revises: dcb90affd769
Create Date: 2023-09-26 22:05:03.138486

"""

# revision identifiers, used by Alembic.
revision = 'e622e2d3a32b'
down_revision = 'dcb90affd769'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
