"""init

Revision ID: ed7b6cdb3a7d
Revises: f6f246000718
Create Date: 2023-09-27 23:34:02.321181

"""

# revision identifiers, used by Alembic.
revision = 'ed7b6cdb3a7d'
down_revision = 'f6f246000718'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
