"""init

Revision ID: eeab15bb5dcc
Revises: 12aa39ebda5e
Create Date: 2023-09-27 01:04:29.499276

"""

# revision identifiers, used by Alembic.
revision = 'eeab15bb5dcc'
down_revision = '12aa39ebda5e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
