"""init

Revision ID: ef674a0c3579
Revises: 029e1cd8d45d
Create Date: 2023-09-26 23:50:54.747848

"""

# revision identifiers, used by Alembic.
revision = 'ef674a0c3579'
down_revision = '029e1cd8d45d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
