"""init

Revision ID: f04e886363e9
Revises: 6a9aac0661ec
Create Date: 2023-09-27 02:05:51.845130

"""

# revision identifiers, used by Alembic.
revision = 'f04e886363e9'
down_revision = '6a9aac0661ec'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
