"""init

Revision ID: f582cc414e33
Revises: ab9c789aaa56
Create Date: 2023-09-27 23:17:35.395669

"""

# revision identifiers, used by Alembic.
revision = 'f582cc414e33'
down_revision = 'ab9c789aaa56'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
