"""init

Revision ID: f6f246000718
Revises: 2b6e59e880e5
Create Date: 2023-09-27 23:24:00.710702

"""

# revision identifiers, used by Alembic.
revision = 'f6f246000718'
down_revision = '2b6e59e880e5'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
