"""init

Revision ID: f7b0a1eaa12c
Revises: 38ea7f697093
Create Date: 2023-09-26 23:12:27.323655

"""

# revision identifiers, used by Alembic.
revision = 'f7b0a1eaa12c'
down_revision = '38ea7f697093'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
