"""init

Revision ID: fcf494ff0cc2
Revises: 9251cccdc35d
Create Date: 2023-09-26 22:35:03.514734

"""

# revision identifiers, used by Alembic.
revision = 'fcf494ff0cc2'
down_revision = '9251cccdc35d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
